FROM python:3.9

# Establecer un directorio de trabajo
WORKDIR /app

# Copiar los archivos necesarios al contenedor
COPY serverc.py /app
COPY requirements.txt /app

# Instalar las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Comando para ejecutar la aplicación
CMD ["uvicorn", "serverc:app", "--host", "0.0.0.0", "--port", "8000"]
