# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npeer.proto\"-\n\x08\x46ileData\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"\x1c\n\x08\x46ileName\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2W\n\x0bPeerService\x12\"\n\nUploadFile\x12\t.FileData\x1a\t.Response\x12$\n\x0c\x44ownloadFile\x12\t.FileName\x1a\t.FileDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'peer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILEDATA']._serialized_start=14
  _globals['_FILEDATA']._serialized_end=59
  _globals['_FILENAME']._serialized_start=61
  _globals['_FILENAME']._serialized_end=89
  _globals['_RESPONSE']._serialized_start=91
  _globals['_RESPONSE']._serialized_end=118
  _globals['_PEERSERVICE']._serialized_start=120
  _globals['_PEERSERVICE']._serialized_end=207
# @@protoc_insertion_point(module_scope)
